name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "tr-ai-torapi" # Replace with your Heroku app name
          heroku_email: "cole.garboski@snhu.edu" # Replace with your Heroku account email
          appdir: "FlaskAPI" # Replace with the directory containing your Flask API code
